export const projectDetails =[
    { "id": 1,
     "description":'Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.',
     "name": 'John Doe',
     "date":"14th sept 2243",
     "isComplete":true,
     },
     { "id": 1,
     "description":'Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.',
     "name": 'John Doe',
     "date":"14th sept 2243",
     "isComplete":true,
     },
     { "id": 1,
     "description":'Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.',
     "name": 'John Doe',
     "date":"14th sept 2243",
     "isComplete":true,
     },
     { 
         "id": 1,
     "description":'Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.',
     "name": 'John Doe',
     "date":"14th sept 2243",
     "isComplete":true,
     },
     { 
     "id": 1,
     "description":'Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.',
     "name": 'John Doe',
     "date":"14th sept 2243",
     "isComplete":true,
 },
  ];
 export  const subscibeDetails =[
      {
         "id": 1,
         "description":'Get working experience to work with this amazing team & in future want to work together for bright future Ideas and also make deposit to freelancer.',
         "name": 'John Doe',
         "projects":34,
         "ideas":78,
         "subscribers":112,
     },
     {
         "id": 1,
         "description":'Get working experience to work with this amazing team & in future want to work together for bright future Ideas and also make deposit to freelancer.',
         "name": 'John Doe',
         "projects":34,
         "ideas":78,
         "subscribers":112,
     },
     {
         "id": 1,
         "description":'Get working experience to work with this amazing team & in future want to work together for bright future Ideas and also make deposit to freelancer.',
         "name": 'John Doe',
         "projects":34,
         "ideas":78,
         "subscribers":112,
     },
     {
         "id": 1,
         "description":'Get working experience to work with this amazing team & in future want to work together for bright future Ideas and also make deposit to freelancer.',
         "name": 'John Doe',
         "projects":34,
         "ideas":78,
         "subscribers":112,
     },
 
 ]